/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/room2.glb -kKS
*/

import { useGLTF, useTexture } from '@react-three/drei';
import { MeshStandardMaterial, sRGBEncoding } from 'three';

export function Room(props) {
  const { nodes } = useGLTF('./models/room2.glb');
  const texture = useTexture('textures/Baked.jpg');
  texture.flipY = false;
  texture.encoding = sRGBEncoding;

  const textureMaterial = new MeshStandardMaterial({ map: texture });
  return (
    <group name='Scene'>
      <mesh
        name='Walls_Floor'
        geometry={nodes.Walls_Floor.geometry}
        material={textureMaterial}
      />
      <mesh
        name='Desk'
        geometry={nodes.Desk.geometry}
        material={textureMaterial}
      />
      <mesh
        name='Leg1'
        geometry={nodes.Leg1.geometry}
        material={textureMaterial}
      />
      <mesh
        name='Leg2'
        geometry={nodes.Leg2.geometry}
        material={textureMaterial}
      />
      <mesh
        name='TV'
        geometry={nodes.TV.geometry}
        material={textureMaterial}
        position={[-2.56, 2.402, -4.309]}
      />
      <mesh
        name='TV_Stand'
        geometry={nodes.TV_Stand.geometry}
        material={textureMaterial}
      />
      <mesh
        name='Sofa'
        geometry={nodes.Sofa.geometry}
        material={textureMaterial}
      >
        <mesh
          name='Oreillers_Bottom'
          geometry={nodes.Oreillers_Bottom.geometry}
          material={textureMaterial}
        />
        <mesh
          name='Oreillers_Top'
          geometry={nodes.Oreillers_Top.geometry}
          material={textureMaterial}
        />
      </mesh>
      <mesh
        name='RubixCube'
        geometry={nodes.RubixCube.geometry}
        material={textureMaterial}
        position={[-2.052, 1.482, -2.611]}
      />
      <mesh
        name='Carpet'
        geometry={nodes.Carpet.geometry}
        material={textureMaterial}
      />
      <mesh
        name='Shelf'
        geometry={nodes.Shelf.geometry}
        material={textureMaterial}
        position={[2.159, 2.435, 5.293]}
      />
      <mesh
        name='Mouse_carpet'
        geometry={nodes.Mouse_carpet.geometry}
        material={textureMaterial}
        position={[-1.183, 1.989, 4.952]}
      />
      <mesh
        name='Mouse'
        geometry={nodes.Mouse.geometry}
        material={textureMaterial}
        position={[-2.23, 1.995, 4.023]}
        rotation={[0, -0.47, 0]}
      />
      <mesh
        name='Computer'
        geometry={nodes.Computer.geometry}
        material={textureMaterial}
        position={[0.777, 0.695, 5.405]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        name='Keyboard'
        geometry={nodes.Keyboard.geometry}
        material={textureMaterial}
        position={[-1.331, 1.993, 4.861]}
        rotation={[-Math.PI, 0.635, -Math.PI]}
      />
    </group>
  );
}

useGLTF.preload('./models/room2.glb');
