/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/room2.glb -kKS
*/

import React, { useRef } from 'react';
import { useGLTF, useTexture } from '@react-three/drei';
import { MeshStandardMaterial, sRGBEncoding } from 'three';

export function Room(props) {
  const { nodes, materials } = useGLTF('./models/room2.glb');
  const texture = useTexture('textures/Baked.jpg');
  texture.flipY = false;
  texture.encoding = sRGBEncoding;

  const textureMaterial = new MeshStandardMaterial({ map: texture });
  return (
    <group {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          name='REF'
          geometry={nodes.REF.geometry}
          material={textureMaterial}
          position={[0, 1.8, 0]}
          scale={[0.5, 1.8, 0.5]}
        />
        <group name='Cube' position={[0, 1, 0]}>
          <mesh
            name='Cube001'
            geometry={nodes.Cube001.geometry}
            material={textureMaterial}
          />
          <mesh
            name='Cube001_1'
            geometry={nodes.Cube001_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name='Cube001_2'
            geometry={nodes.Cube001_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name='Cube001_3'
            geometry={nodes.Cube001_3.geometry}
            material={textureMaterial}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('./models/room2.glb');
